import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import products from '../../products.json';


//
export default function Product() {
    return (
      
     <>   
        <Head>
          <title>Site société | Boutique </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="lkeyword" content="next" />
          <link rel="icon" href="/favicon.ico" />
  
          <link rel="preconnect" href="https://app.snipcart.com" />
          <link rel="preconnect" href="https://cdn.snipcart.com" />
          <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css" />
        </Head>
        
  
        <main className="main" >
          {/* className={styles.main} */}
         
  
          <div className="grid">
             {/* className={styles.grid} */}
          {products.map(product => {
            return (          
  
              <div key={product.id} className="card">
                {/* className={styles.card} */}
                <img
                src={product.image}
                alt={`Preview of ${product.title}`} 
                height="253"
                width="253"                  
                />               
                <h3>{ product.title }</h3>
                <p>{ product.description }</p>
                <p>${ product.price }</p>
                <p>
                  {/*  className="snipcart-add-item"} */} 
                  <button
                    className="snipcart-add-item"                   
                    data-item-id={product.id}
                    data-item-image={product.image}
                    data-item-name={product.title}
                    data-item-price={product.price}
                    data-item-description={product.description}                  
                  >Add to Cart</button>
                </p>
                <Link 
                href={'/product/' + product.id} 
                key={product.id} > 
                Plus de détails
                </Link>
              </div>
            );
          })}
          </div>
        </main>
  
        </> 
    )
  }
