import Head from 'next/head';
const  About = () => {
    return ( 
        <>
        <Head>
        <title>Snipcart Store | About </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="lkeyword" content="next" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css" />
      </Head>
      <main className='main' >
      
      <div className="container">
      <h1>Site Société version NEXTjs</h1>
            
            <p>Votre site E-Commerce sera présent sur le web avec cette solution E-commerce pour vendre facilement vos produits. 
                C&apos;est une solution très complète. </p>
                <p> Vous disposerez de plusieurs pages pour présenter en détails votre société. </p>
                <p> Vous présentez votre société avec une géolocalisation, la présentations de vos produits, les nouveautés avec un lien Instagram, twitter et facebook.  </p>
                <p>   Vos clients peuvent vous contacter avec votre propre adresse mail. </p>
                <p>   Une page d'administration privée et sécurisée vous permettra d'ajouter et de gérer vos produits, vos nouveautés, etc.  </p>
                <p>   J'ai utilisé NEXTjs c'est un framework React super efficace et très dynanmique  mais d'autres techniques sont possibles ( Jekyll, WebApp, NodeJS/Angular). </p>
            <p>
                <strong>Un exemple en Jekyll du site est dispo à cette adresse : 
                <a href="https://lvdesign.github.io/sitesociete/">site societe</a>
                </strong>
            </p>




<h1><em>Company's Website with NEXTjs</em></h1>

<p>Your E-Commerce site will be present on the web with this E-commerce solution to easily sell your products. It is a very complete solution.</p>
<p>You will have several pages to present in detail your company.</p>
<p>You present your company with a geolocation, presentations of your products, news with a link Instagram, twitter and facebook.
</p>
<p>Your customers could contact you with your own email address.</p>
<p>A secure private administration page will allow you to add and manage your products, news, etc.</p>
<p>I used NEXTjs it&apos;s a super efficient and very dynamic React framework but other techniques are possible (Jekyll, WebApp, NodeJS/Angular).</p>
<p><em><strong>An example Jekyll of the site at this address :  
    <a href="https://lvdesign.github.io/sitesociete/ " alt="" >site societe</a></strong> </em>
    </p>




<h3>Snipcart: "We offer fair, scalable pricing for small businesses."</h3>

<p>The solution offered by <a href="https://snipcart.com/list-ecommerce-payment-gateways">SnipCart</a>is really very effective and quite reassuring for an online purchase. Many payment solutions are available: Stripe, PayPal, Payroll, Authorize.Net, Braintree Payments, Mollie, Pin Payments, Paysafe, Square.</p>

<p>Confident of their solution, the team proposes a comparison with the other systems of payment, will see this very interesting comparison: <a href="https://snipcart.com/compare">Comparison of solution of payment.</a></p>


<p>For more information, visit this page allowing you to understand the price of this service:  <a href="https://snipcart.com/pricing">SnipCart: Pricing.</a>

</p>

      </div>
      

            
        </main>
        </>
        
     );
}
 
export default About;