import Head from 'next/head';
import Link from 'next/link';
import Script from 'next/script'
import Image from 'next/image';
import products from '../products.json';



// Home page
export default function Home() {
  return (

    <>
      <Head>
        <title>Site Société | Home </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keyword" content="next" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css" />
       </Head>
      

      <main className="main">       
        
{/*  <!-- 1/ Parrallax Image large --> /images/picto/pictoF.svg" */}
<div className="masthead white-text" role="img" aria-label="Image Description">     
      <h1 className="header">Site Société</h1>
        <h4 className="center mb-5">
        <i>Bonjour, vous êtes sur la démonstration du "site Société" de LVdesign. Présenter vos produits sur le net. Bonne
          découverte !</i>
        </h4>
        <p><Link href="/#contact"><a className="waves-effect waves-lightbtn btn-small green" >En savoir plus ?</a></Link></p>
</div>

{/* <!--Section: Best Features--> */}
<div className="container">

  <div className="row" id="services">
    <h2 className="center mb-5 font-weight-bold">LVdesign vous propose …</h2>

    <h4 className="center mb-5">
      Une solution E-commerce avec <a href="https://snipcart.com/"
        alt="Snipcart : Professionally crafted shopping cart platform, for big & small businesses alike !">Snipcart</a>
      pour présenter facilement et pour un prix sans concurences vos produits sur le web. N'hésitez pas à consulter <a
        href="https://lvdesign.github.io/mylvdesign/">LVdesign</a> mon studio de réalisation de site pour plus d'informantion !
    </h4>
    

    <div className="col s12 m4">
      <div className="center">
        <i className="large material-icons sr-icons green-text">person_add</i>
        <h5 className="propose">Experiences</h5>
        <p className="light center flow-text">Fusce nisl sapien, pellentesque ac vehicula sit amet, tincidunt in dui. Nunc dignissim convallis malesuada. Vivamus venenatis sit amet ligula a eleifend. In venenatis dolor eros, convallis dictum orci facilisis vel.</p>
      </div>
    </div>

    <div className="col s12 m4">
      <div className="center ">
        <i className="large material-icons sr-icons green-text">favorite</i>
        <h5 className="propose">Happiness</h5>
        <p className="light center flow-text">Vestibulum eget fermentum eros. Integer a quam eget ante ultrices luctus. Integer a consectetur nisl. Mauris vulputate lectus tristique vestibulum eleifend. Cras egestas porta massa at pellentesque. Aliquam cursus enim justo, ac viverra ipsum maximus. Sed nisi justo, faucibus sit amet eros sed, rutrum interdum nibh.</p>
      </div>
    </div>

    <div className="col s12 m4">
      <div className="center ">
        <i className="large material-icons sr-icons green-text">restore</i>
        <h5 className="propose">Services</h5>
        <p className="light center flow-text">Donec eget eleifend nunc. Aenean imperdiet porttitor erat, id tempus elit aliquam at. Duis sed tellus ex. Vestibulum quis dui eros. Pellentesque aliquet at ipsum ut accumsan.</p>
      </div>
    </div>
  </div>

</div>

{/* <!--Section: Produits --> */}
<div className="container" id="produits">

  <div className="row">

    <h2 className="mb-2 font-weight-bold center">Nos produits par categories</h2>

    <div className="col s12 m6">
      <div className="card">
        <div className="card-image">
          <picture>
            <source srcSet="/images/products/in-plant-2.webp" type="image/webp" media="(min-width: 10em)" />
            <source srcSet="/images/products/in-plant-2.png" type="image/png" media="(min-width: 10em)" /> 
            <Image
              src="/images/products/in-plant-2.png"
              alt="Plantes d'interieures"              
              width={244}
              height={244}
            />
            
          </picture>
          <Link href="/product">
            <a className="btn-floating halfway-fab waves-effect waves-light red accent-1" href="">
            <i className="material-icons small">shopping_cart</i>
            </a>
          </Link>
          
           
        </div>
        <div className="card-content">
          <span className="card-title">Plantes d'interieures</span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit maiores nam,
            aperiam minima assumenda deleniti hic.</p>
        </div>
      </div>
    </div>

    <div className="col s12 m6">
      <div className="card">
        <div className="card-image">
          <picture>
            <source srcSet="/images/products/ou-plant-0.webp" type="image/webp" media="(min-width: 10em)" />
            <source srcSet="/images/products/ou-plant-0.png" type="image/png" media="(min-width: 10em)" />

            <Image
              src="/images/products/ou-plant-0.png"
              alt="Plantes d'exterieures"              
              width={244}
              height={244}
            />
          </picture>

          <Link href="/product">
            <a className="btn-floating halfway-fab waves-effect waves-light red accent-1" href="">
            <i className="material-icons small">shopping_cart</i>
            </a>
          </Link>

        </div>
        <div className="card-content">
          <span className="card-title">Plantes d'exterieures</span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit maiores nam,
            aperiam minima assumenda deleniti hic.</p>
        </div>
      </div>
    </div>

    <div className="col s12 m6">
      <div className="card">
        <div className="card-image">
          <picture>
            <source srcSet="/images/products/ambiance-out-1.webp" type="image/webp" media="(min-width: 10em)" />
            <source srcSet="/images/products/ambiance-out-1.png" type="image/png" media="(min-width: 10em)" />
            <Image
              src="/images/products/ambiance-out-1.png"
              alt="Meubles de jardin"              
              width={244}
              height={244}
            />
          
          </picture>
         
          <Link href="/product">
            <a className="btn-floating halfway-fab waves-effect waves-light red accent-1" href="">
            <i className="material-icons small">shopping_cart</i>
            </a>
          </Link>
        </div>
        <div className="card-content">
          <span className="card-title">Meubles de jardin</span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit maiores nam,
            aperiam minima assumenda deleniti hic.</p>
        </div>
      </div>
    </div>

    <div className="col s12 m6">
      <div className="card">
        <div className="card-image">
          <picture>
            <source srcSet="/images/products/ambiance-in-1.webp" type="image/webp" media="(min-width: 10em)" />
            <source srcSet="/images/products/ambiance-in-1.png" type="image/png" media="(min-width: 10em)" />
            <Image
              src="/images/products/ambiance-in-1.png"
              alt="Décorations d'interieuresn"              
              width={244}
              height={244}
            />
          
          </picture>
          

          <Link href="/product">
            <a className="btn-floating halfway-fab waves-effect waves-light red accent-1" href="">
            <i className="material-icons small">shopping_cart</i>
            </a>
          </Link>
        </div>
        <div className="card-content">
          <span className="card-title">Décorations d'interieures</span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit maiores nam,
            aperiam minima assumenda deleniti hic.</p>
        </div>
      </div>
    </div>



   {/*  <!-- Test cat evolue --> */}

    {/* <!-- s12 m4 l3--> */}

  </div>
</div>

{/* <!--Section: Acualités --> */}
<div className="container" id="actu">
  <div className="row">
    <h2 className="mb-5 center">Gallerie de nos projets </h2>

    <div className="carousel col s12 m6">
      <h5 className="center">Instagram mood </h5>
      <a className="carousel-item" href="#one!">
        <picture>
          <source srcSet="/images/insta/insta1.webp" type="image/webp" media="(min-width: 10em)" />
          <source srcSet="/images/insta/insta1.png" type="image/png" media="(min-width: 10em)" /> 

          <Image
              src="/images/insta/insta1.png"
              alt="1-textes Décorations d'interieures"              
              width={244}
              height={244}
            />
        </picture>        
      </a>
      <a className="carousel-item" href="#two!">
        <picture>
          <source srcSet="/images/insta/insta2.webp" type="image/webp" media="(min-width: 10em)" />
          <source srcSet="/images/insta/insta2.png" type="image/png" media="(min-width: 10em)" />
          <Image
              src="/images/insta/insta2.png"
              alt="2-textes Décorations d'interieures"              
              width={244}
              height={244}
            />

        </picture>
      </a>
      <a className="carousel-item" href="#three!">
        <picture>
          <source srcSet="/images/insta/insta3.webp" type="image/webp" media="(min-width: 10em)" />
          <source srcSet="/images/insta/insta3.png" type="image/png" media="(min-width: 10em)" />
          <Image
              src="/images/insta/insta3.png"
              alt="3-textes Décorations d'interieures"              
              width={244}
              height={244}
            />
         
        </picture>
      </a>
      <a className="carousel-item" href="#four!">
        <picture>
          <source srcSet="/images/insta/insta1.webp" type="image/webp" media="(min-width: 10em)" />
          <source srcSet="/images/insta/insta1.png" type="image/png" media="(min-width: 10em)" />
          <Image
              src="/images/insta/insta1.png"
              alt="4-textes Décorations d'interieures"              
              width={244}
              height={244}
            />
        </picture>
      </a>
      <a className="carousel-item" href="#five!">
        <picture>
          <source srcSet="/images/insta/insta2.webp" type="image/webp" media="(min-width: 10em)" />
          <source srcSet="/images/insta/insta2.png" type="image/png" media="(min-width: 10em)" />
          <Image
              src="/images/insta/insta2.png"
              alt="5-textes Décorations d'interieures"              
              width={244}
              height={244}
            />
        </picture>
      </a>

    </div>

    <div className="col s12 m6">
      <a className="twitter-timeline" href="https://twitter.com/lvdesign" data-widget-id="352010766683082754"
        alt="le compte de lvdesign sur twitter, venez tweeter…"
        title="le compte de lvdesign sur twitter, venez tweeter…">Tweets de @lvdesign</a>
     {/*  <!--tweet js--> */}
      <Script id="my-script-Twitter">{`!function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https'; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = p + "://platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs); } }(document, "script", "twitter-wjs"); `}</Script>
    </div>


  </div>


</div>

{/* <!--Section: Contact --> */}
<div className="container" id="contact">
  <div className="row">
    <h2 className="mb-5 center">Nous contacter</h2>

    <form className="col s12">

      <div className="row">
        <div className="input-field col s6">
          <i className="material-icons prefix">account_circle</i>
          <input id="first_name" type="text" className="validate" />
          <label htmlFor="first_name">Nom</label>
        </div>
        <div className="input-field col s6">
          <input id="last_name" type="text" className="validate" />
          <label htmlFor="last_name">Prénom</label>
        </div>
      </div>

      <div className="row">
        <div className="input-field col s6">
          <i className="material-icons prefix">email</i>
          <input id="email" type="email" className="validate" />
          <label htmlFor="email">Email</label>
          <span className="helper-text" data-error="wrong" data-success="right">Helper text</span>
        </div>

        <div className="input-field col s6">
          <i className="material-icons prefix">phone</i>
          <input id="tel" type="tel" className="validate" />
          <label htmlFor="tel">Telephone</label>
          <span className="helper-text" data-error="wrong" data-success="right">Helper text</span>
        </div>

      </div>

      <div className="row">
        <div className="input-field col s12">
          <i className="material-icons prefix">comment</i>
          <textarea id="message" type="text" className="materialize-textarea"></textarea>
          <label htmlFor="message">Message</label>
        </div>
      </div>
      <div className="row center">
        <button className="green btn waves-effect waves-light" type="submit" name="action">Envoyez votre message
          <i className="material-icons right">send</i>
        </button>
      </div>
    </form>
  </div>
</div>

{/* <!--Section: map--> */}
{/* <!-- 1/ Parrallax Image large --> 
style="height: 400px

*/}
<div className="container">
  <div className="row">
    <h2 className="mb-5 center">Où nous trouver ?</h2>
    <div id="map-container" className="z-depth-1-half map-container mb-5" > </div>
  </div>

</div>

{/* <!-- Google Maps settings --> */}
  
<Script id="my-script-Google">
    {`
    (function(){
      'use strict';

      function regular_map() {
        const var_location = new google.maps.LatLng(48.862725, 2.287592);
    
        var var_mapoptions = {
          center: var_location,
          zoom: 14
        };
    
        var var_map = new google.maps.Map(document.getElementById("map-container"),
          var_mapoptions);
    
        var var_marker = new google.maps.Marker({
          position: var_location,
          map: var_map,
          title: "Paris"
        });
      }
      regular_map();

    })();
    `}
    
  
  
</Script>

<div className="container">

  <div className="row">
    <div className="col s6 left-align">
      <h6 className=" ">Restez connecté avec nos réseaux sociaux!</h6>
    </div>

    <div className="col s6 right-align">
     {/*  <!--Facebook--> */}
      <a href="#"><i className="fab fa-facebook-square fa-3x green-text "></i></a>
     {/*  <!--Twitter--> */}
      <a href="#" className="tw-ic"><i className="fab fa-twitter-square fa-3x green-text"></i></a>
      {/* <!--Instagram--> */}
      <a href="#" className="ins-ic"><i className="fab fa-instagram fa-3x green-text"></i></a>
    </div>
  </div>
</div>       
</main>

     
          

    </>    
    )
}
