import Head from 'next/head';
const  Offline = () => {
    return ( 
        <>
        <Head>
        <title>Snipcart Store |Offline </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="lkeyword" content="next" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css" />
      </Head>
      <main className='main' >
            <h1>Offline Page</h1>
            <p>Page service worker</p>
        </main>
        </>
        
     );
}
 
export default Offline;